Changed Bretonia Gunboat, Destroyer, & Battleship
Freelancer-Sirius-Revival/FLSR pull request #411
Opened 2023-02-26 09:57 UTC by FireFlyEx

Here is the first set of ships to be updated:

Bretonian Gunboat
Bretonian Destroyer
Bretonian Battleship

Modified shiparch entries, engine entries, and appropriate cockpit files.

2023-02-26 11:32 UTC, erikroe commented
I'll be checking them out in a moment. Though, the speeds of the ships were intentionally set beforehand on what they were to support their roles in combat. Please change those back to the original values.

2023-02-26 11:35 UTC, erikroe commented
Also on the Linear Drag; For the BR Gunboat it was intentional to have a portion of it to be set on the engine and one portion on the ship. The reason for this: Reducing the effect of engine kill. Engine kill on capital ships is limited by setting Linear Drag on the ship instead of the engine. This prevents them from using it, effectively. For the big guns to not have suddenly a larger range when dropping from cruise by using engine kill. For Gunboats this however was partially allowed. That is why their linear drag values were distributed on ship and engine. I would like to see that behaviour being kept.

2023-02-26 12:49 UTC, erikroe commented
I tested the ships now. The Bretonian Gunboat was far too much nerfed. It's role as anti-fighter/freighter support is impossible to fulfill now with this far lower turning rates.

2023-02-26 22:45 UTC, erikroe commented
Tested with the adjusted BR Gunboat settings again. It feels quite odd from before. The movement appears stiff. Like you said, more like a heavy fighter. I think it has to do with the camera settings you applied to it.
I have one question though: Why was the camera movements and all in the shiparch even changed? I thought it to be just good as it was before. Same as the steering speed really.

2023-02-26 22:53 UTC, erikroe requested changes

2023-02-26 22:53 UTC, erikroe commented on DATA/SHIPS/shiparch.ini
> +linear_drag = 24000
The increased linear drag here and at the battleship reduce the feeling of them being heavy. They break too fast, taking away the illusion of inertia.

2023-02-27 05:44 UTC, FireFlyEx commented
> 

One of the things I am doing is normalizing the data for capital ships. Changing the camera settings gives more weight to the ship and less wild turning in the camera view, which tends to be less disorienting to the player and helps those who suffer from motion sickness (like me). I can find a medium point if you like? Or I can forget about all of this stuff since you don't see any of it as beneficial. I can work on something else.

2023-02-27 05:55 UTC, closed without merging