Balancing Exotic Weapons & Sound Additions
Freelancer-Sirius-Revival/FLSR pull request #443
Opened 2023-03-11 19:02 UTC by Worldwave

Rebalanced damage values for exotic codenames and the anti-shield missiles Buffed FALLEN DRAGON
Added new animations to ATRAX
Added 4 new sound files

2023-03-11 19:25 UTC, XxSARGExX requested changes
Missing pi_particle_03_proj in effects ini

2023-03-11 19:25 UTC, XxSARGExX commented on DATA/FX/effects.ini
> -nickname = pi_particle_03_proj
pi_particle_03_proj is exchanged with pi_particle_05_flash (pi_particle_03_proj not there anymore)

2023-03-11 19:27 UTC, Worldwave commented
Added back

2023-03-11 19:31 UTC, XxSARGExX approved these changes

2023-03-11 19:31 UTC, merged

2023-03-17 16:24 UTC, erikroe commented on DATA/FX/beam_effects.ini
> +; ATRAX Xenos Heavy Particle Weapon
Would be nice to have the comments actually at the right spot above the thing, and not below.

2023-03-17 16:24 UTC, erikroe commented on DATA/FX/effects.ini
> +; ATRAX Xenos Heavy Particle Weapon
Same with the comment being at the wrong spot