Changing Freighter Weapons Slot for adding a Minin Device Slot
Freelancer-Sirius-Revival/FLSR pull request #799
Opened 2024-04-08 15:49 UTC by XxSARGExX

All Freighter Medium Slots are changed to Heavy Slots

Exception: Mule

Mining Device Added on following Slots:

Rhino: HpWeapon01
Clydestale: HpWeapon01
Humpback: HpTurret05
Drone: HpTurret06
Mule: HpTurret01
Dromedary: HpWeapon01

Armored Transport: HpTurret07

2024-04-08 23:49 UTC, erikroe commented on DATA/SHIPS/shiparch.ini
> +; Shields: 1X
1 X with a space between

2024-04-09 11:53 UTC, erikroe requested changes

2024-04-09 11:53 UTC, erikroe commented on DATA/SHIPS/shiparch.ini
>  ;
1 X Shield and Mining Device are not listed in the lines below here

2024-04-09 11:53 UTC, erikroe commented on DATA/SHIPS/shiparch.ini
>  ;
Mining Device missing in all the "reduced" statistics

2024-04-14 09:56 UTC, erikroe requested changes
ids_info2 for all the Freighters with Mining Equipment  need the version where Mining Equipment is listed. See the top of the shiparch.ini file.

Also, the Mining Ship and CSV both do not have Mining Equipment listed. They have them instead as 1 X gun in their stats. Needs to be adjusted.

2024-04-14 15:10 UTC, erikroe requested changes

2024-04-14 15:10 UTC, erikroe commented on DATA/SHIPS/shiparch.ini
> +; 1
Mining Device added here, but you forgot to remove the 1 X above

2024-04-14 15:10 UTC, erikroe commented on DATA/SHIPS/shiparch.ini
> +; Mining Device:
This is just an incomplete solution. Now you added this to every ship's statistics. So if you go for this, _every_ ship must now have a stats entry for Mining Devices.
Or make a copy of this stats entry for just those ships that have actual mining devices.

2024-04-18 19:56 UTC, Caenen commented on DATA/SHIPS/shiparch.ini
> -;
Space missing

2024-04-18 20:08 UTC, erikroe requested changes

2024-04-18 20:08 UTC, erikroe commented on DATA/SHIPS/shiparch.ini
> +;
There is a space missing here. It must be `; `

2024-04-18 20:16 UTC, erikroe approved these changes

2024-04-18 20:25 UTC, merged