Changes to capital energy turrets, fix to Kusari battleship's lost M slot
Freelancer-Sirius-Revival/FLSR pull request #890
Opened 2024-08-28 18:23 UTC by Caenen

Increased speed and added dispersion to military AA turrets of large ships (civilian unchanged thus far), addessing https://github.com/Freelancer-Sirius-Revival/FLSR/issues/885. In testing the current iteration performed very well against fighters and especially at shooting down missiles/nomad torpedos coming in to you (which previously would often manage to connect despute several seconds of shooting at them).

Additional changes to the bigger turrets are pick-and-choose, they should improve some of the current clarity/useability issues however.

A fix to the Kusari battleship's M gun in the equipment dealer is included, including the ships' inforcards.

A change to give NPC loadouts alternate variants of main battery turrets that fire on the NPC's priority target instead of any closest target in their field of view, as suggested in issues/823, has been tested for this batch but is iceboxed for now.

2024-08-28 18:56 UTC, erikroe requested changes
Misses the stats part in the weapons descriptions about dispersion

2024-08-28 19:25 UTC, Caenen commented
Added requested changes

2024-08-28 19:44 UTC, erikroe approved these changes

2024-09-13 00:04 UTC, erikroe approved these changes
Looks fine on paper. Still want to see it tested also in PvP, @Caenen

2024-09-13 18:23 UTC, erikroe approved these changes

2024-09-13 18:24 UTC, merged