Winter event
Freelancer-Sirius-Revival/FLSR pull request #976
Opened 2024-12-08 13:27 UTC by XxSARGExX

Featurelist:

General:
- Adding Winter Warden Spawn zones in Tau-31 (Ice Asteroids)
- Adding Winter Warden Base and HQ in Tau-31 (Behind harris) as well asl Tau-37 (Between the suns)
- Adding New Winter Warden Ice Asteroids (Mineable Snowballs)
- Adding new Winter Warden Encounter
- Adding new Bomber AI for Winter Warden
- Adding new Transport and Train loadouts
- Adding new Train wreckage in Tau-31
- Adding new Effects

Items:
- Adding Christmas Present as new lootbox
- Adding Naughty Present as new lootbox
- Adding Snowballs as crafting material (Special)
- Adding new SANTA VON CLAUSSEN Equipment 
- Adding Winter Warden Equipment

Changes:
- Adding Snowballs to some Ice Asteroid Drops

Fuse:
- Adding new Small Station Explosion Fuse

2024-12-08 14:13 UTC, erikroe requested changes

2024-12-08 14:13 UTC, erikroe commented on Freelancer/DATA/SOLAR/ASTEROIDS/bw10_ice_crystal_field.ini
> +exclusion = ZONE_Ew01_Exclusion_ice_bw10_Wardens01
ew01 or bw10?

2024-12-08 14:13 UTC, erikroe commented on Freelancer/DATA/SOLAR/ASTEROIDS/ew01_wardens_mineable_asteroids.ini
> +asteroid_loot_commodity = commodity_niobium
Would it be nice to have snowballs be actual loot items here?

2024-12-08 14:13 UTC, erikroe commented on Freelancer/DATA/UNIVERSE/SYSTEMS/BW10/bw10.ini
> +nickname = ZONE_Ew01_Exclusion_ice_bw10_Wardens01
ew01? But this is BW10

2024-12-08 14:13 UTC, erikroe commented on Freelancer/DATA/UNIVERSE/SYSTEMS/BW10/bw10.ini
> +; The abandoned carriage of Krampus, it got stranded while he was on his way to punish the naughty ones. you found a recipe in the cockpit.\n
You find a recipe in the cockpit.

2024-12-08 14:13 UTC, erikroe commented on Freelancer/DATA/UNIVERSE/SYSTEMS/BW10/bw10.ini
> +; • 200 Snowballs
The x is missing here

2024-12-08 14:19 UTC, XxSARGExX commented on Freelancer/DATA/EQUIPMENT/commodity_equip.ini
> +; /craft Christmas Key <amount>
Thats not true, your crafting plugin doesnt look on the IDS Name it looks on the configuration header name in the brackets [XYZ]

2024-12-08 14:20 UTC, erikroe commented on Freelancer/DATA/EQUIPMENT/commodity_equip.ini
> +; /craft Christmas Key <amount>
Right, sorry, I confused it with the loot boxes

2024-12-08 15:47 UTC, erikroe requested changes

2024-12-08 15:47 UTC, erikroe commented on Freelancer/DATA/EQUIPMENT/engine_equip.ini
> +; \m\bSANTA VON CLAUSSEN’S ENGINE Engine\B
It says "ENGINE engine". These duplications should be removed. Same for the following engine infocards

2024-12-08 15:47 UTC, erikroe commented on Freelancer/DATA/UNIVERSE/SYSTEMS/BW10/bw10.ini
> +; The abandoned carriage of Krampus, it got stranded while he was on his way to punish the naughty ones. You find a recipe in the cockpit.\n
Little correction: You’ll find

2024-12-09 16:27 UTC, erikroe requested changes

2024-12-09 16:27 UTC, erikroe commented on Freelancer/DATA/EQUIPMENT/engine_equip.ini
> +; This modified civilian engines is commonly used by more experienced pilots of the Winter Wardens, it provides high efficency and speed for commercial and tactical usage.
This needs the same corrections as the infocard above

2024-12-09 16:27 UTC, erikroe commented on Freelancer/DATA/EQUIPMENT/engine_equip.ini
> +; Winter Warden Transport Engine ($class)
Better to shorten it to "Wardens Transport Engine"

2024-12-09 16:27 UTC, erikroe commented on Freelancer/DATA/EQUIPMENT/engine_equip.ini
> +; \m\bWinter Warden Engine\B
Winter Wardens Transport Engine

2024-12-09 16:27 UTC, erikroe commented on Freelancer/DATA/EQUIPMENT/engine_equip.ini
> +; Winter Warden Train Engine ($class)
Same as with the Transport engine

2024-12-09 16:27 UTC, erikroe commented on Freelancer/DATA/EQUIPMENT/weapon_equip.ini
> +; \m\b“Heaven’s point” Wardens Weapon\B
Capital P for point

2024-12-09 16:27 UTC, erikroe commented on Freelancer/DATA/EQUIPMENT/weapon_equip.ini
> +; \m\b“Heaven’s point MKII” Wardens Weapon\B
Point with capital P

2024-12-09 16:27 UTC, erikroe commented on Freelancer/DATA/EQUIPMENT/weapon_equip.ini
> +; \cYellow\i\bHappy Hollidays\B\I\C
Holidays with one L and it is missing the ! at the end like the other equips have it.

2024-12-10 11:20 UTC, erikroe approved these changes

2024-12-10 11:20 UTC, merged